name: Build Flutter AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.CM_KEYSTORE }}" | base64 -d > android/app/upload-keystore.jks

      - name: Set up key.properties
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.CM_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.CM_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.CM_KEY_PASSWORD }}" >> android/key.properties

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
